### ISSUE TITLE
Feature Request: Sentence tokenizer

### ISSUE THREAD

**Issue by aviks** [JuliaText/TextAnalysis.jl#1]
It would be nice to have a sentence tokenizer in this package.

**Comment by ksteimel** [comment]
Do tokenization tools still need work? I would love to help.

**Comment by aviks** [comment]
Yes. An implementation of a sentence tokenisation (maybe Punkt?) would be much appreciated.

**Comment by ksteimel** [comment]
Okay cool. I'm working on that. Can I be added as a collaborator?

I will first implement punkt's approach. I'd also like to use the Universal Dependency Treebank to train a supervised model for sentence splitting. I'm uncertain how sentence tokenized documents should fit into the document classes that are currently used. Any of the document types could be sentence split but I don't know if introducing a new sentence split version of each one is advisable.

**Comment by aviks** [comment]
Maybe a single `SentencesDocument`

**Comment by aviks** [comment]
This has been done using WordTokenizers.jl
