### ISSUE TITLE
Extra empty token in lexicon 

### ISSUE THREAD

**Issue by lejon** [JuliaText/TextAnalysis.jl#10]
If I create a text file which consists of the string "1 2" (not including the quotes, my  lexicon always contains the "empty token" (""). Even if I try to remove the word "" it is still there. Is this the intended behaviour? It causes problems for me because in my LDA implementation I get the word "" in my topics.

Example: 

$ cat docs/Sample1.txt 
1 2
$ cat text_analysis_etoken.jl 
using TextAnalysis
crps = DirectoryCorpus("docs")
standardize!(crps, StringDocument)
remove_words!(crps, [""])
update_lexicon!(crps)
println("Dictionary is: " \* string(lexicon(crps)))
println("Corpus contains: " \* string(length(crps)) \* " documents")

$ julia text_analysis_etoken.jl

Corpus's lexicon contains 3 tokens
Corpus's index contains 3 tokens
Dictionary is: ["1"=>1,"2"=>1,""=>2]
Corpus contains: 1 documents

Best Regards
-Leif

**Comment by dellison** [comment]
For what it's worth, I wasn't able to reproduce this issue.

**Comment by aviks** [comment]
Needs some tests, and closing if no longer a problem.
