### ISSUE TITLE
Implement Named Entity Recognition (NER)

### ISSUE THREAD

**Issue by aviks** [JuliaText/TextAnalysis.jl#117]
*Papers*

"Neural Architectures for Named Entity Recognition" - https://arxiv.org/abs/1603.01360
"End-to-end Sequence Labeling via Bi-directional LSTM-CNNs-CRF" - https://arxiv.org/abs/1603.01354

**Comment by npochhi** [comment]
Hi! I would like to work on this.

**Comment by surya2191997** [comment]
HI @aviks , I have read the papers and am interested to work on this. Can you give some pointers on how to start?

**Comment by Ayushk4** [comment]
@oxinabox @aviks
I am working on implementing the second paper - "End-to-end Sequence Labeling via Bi-LSTM-CNNs-CRF"

I have obtained the CoNLL 2003 Dataset for language independent NER Tagging.
So far I have written the code for loading dataset and converting into tagging scheme of BIOES.

I am working on [this repository](https://github.com/Ayushk4/NER_Tagger) for the implementation.

I am currently preparing a prototype for how the model would look like. I would like it to be reviewed once it is done.

**Comment by Ayushk4** [comment]
I guess this has been addressed by #167 .
