### ISSUE TITLE
Can a new release be tagged?

### ISSUE THREAD

**Issue by tanmaykm** [JuliaText/TextAnalysis.jl#139]
Can a new release be tagged? These seem useful to have: https://github.com/JuliaText/TextAnalysis.jl/pull/104 https://github.com/JuliaText/TextAnalysis.jl/pull/138

**Comment by tanmaykm** [comment]
@aviks ?

**Comment by aviks** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/22601
