### ISSUE TITLE
Need API documentation

### ISSUE THREAD

**Issue by ViralBShah** [JuliaText/TextAnalysis.jl#146]
I found the docs quite useful, but I couldn't find any using the command line `help` at the API level. It would be nice to have some documentation for the common functions at the very least.

**Comment by Ayushk4** [comment]
I have this as a part of my GSoC stretch goals. I will be happy to work on this, once I am done with my exams in a week.

**Comment by laschuet** [comment]
If I am not mistaken, @aquatiko started adding the API documentation in #147. Maybe you can join forces.

**Comment by Ayushk4** [comment]
Sure! That would be great.

What do you think @aquatiko?

**Comment by aquatiko** [comment]
Fine with me... We both are having exams in the coming days... Better finish it after that!!

**Comment by Ayushk4** [comment]
Cool ! Good Luck for your exams. :+1:
