### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by kimttfung** [JuliaText/TextAnalysis.jl#177]
Hello. I was just wondering whether a release can be tagged because the NaiveBayes Classifer is currently not implemented to the latest release (v0.6.0). Thank you very much.
@ranjanan

**Comment by ranjanan** [comment]
@fungktt was trying to run code from the documentation: https://juliatext.github.io/TextAnalysis.jl/dev/classify/

**Comment by ranjanan** [comment]
@fungktt could you please rename the issue to "Tag a new release" ?

**Comment by Ayushk4** [comment]
@fungktt For the time being you can work from the master branch `pkg> add TextAnalysis#master`, till the new release is tagged.

**Comment by aviks** [comment]
tagged now.
