### ISSUE TITLE
Docs and docstring for Sentiment Analysis model needs fixing

### ISSUE THREAD

**Issue by Ayushk4** [JuliaText/TextAnalysis.jl#182]
The sentiment model [`docs`](https://juliatext.github.io/TextAnalysis.jl/latest/features/#Sentiment-Analyzer-1) and [`docstrings`](https://github.com/JuliaText/TextAnalysis.jl/blob/f11877268ba3911b30f7b13c549411a08cd380ad/src/sentiment.jl#L85) need minor fixing

`julia> model = SentimentAnalyser()`
`julia> model(doc)` or `julia> model(doc, handle_unknown)`

Thanks to @fungktt for pointing this out in slack.

**Comment by fungktt** [comment]
Thanks! @Ayushk4

**Comment by Ayushk4** [comment]
Fixed in #184 .
