### ISSUE TITLE
NaiveBayesClassifier scope error.

### ISSUE THREAD

**Issue by PseudoCodeNerd** [JuliaText/TextAnalysis.jl#192]
```julia
julia> using TextAnalysis: NaiveBayesClassifier, fit!, predict
ERROR: UndefVarError: NaiveBayesClassifier not defined
```
and 
```julia
julia> model = NaiveBayesClassifier()
ERROR: UndefVarError: NaiveBayesClassifier not defined
Stacktrace:
 [1] top-level scope at REPL[10]:1
```
The former snippet is a copy pasta from the [Docs](https://juliatext.github.io/TextAnalysis.jl/latest/classify/). I also tried enclosing it in a `let-end` loop but it still doesn't work.

I have `[a2db99b7] TextAnalysis v0.6.0` in my working environment.

This isn't the case with `model = SentimentAnalyser()`.

Any help would be appreciated.

**Comment by vbaidin** [comment]
I have the same problem.

**Comment by janghaludu** [comment]
It should work if you install the master branch.
pkg> add TextAnalysis#master  should do the trick.
