### ISSUE TITLE
APIs to avoid datatype constraint between CorpusLoaders.jl and TextAnalysis.jl

### ISSUE THREAD

**Issue by tejasvaidhyadev** [JuliaText/TextAnalysis.jl#195]
`CorpusLoaders.jl` APIs can not be directly used because of datatype constraint input require in Avg Perceptron POS  and other models . I think we can provide new methods in Avg Perceptron POS model to make it compatible with `CorpusLoaders.jl`.

**Comment by Ayushk4** [comment]
Can you give an example/code snippet on what you expect and what changes you suggest? I am not able to get what changes you are trying to propose to TextAnalysis.jl? Though from what you say here, it seems that these changes would be better made to CorpusLoaders.jl rather than this package.

**Comment by tejasvaidhyadev** [comment]
I am closing the issue. I think it will be too specific if we do it here
