### ISSUE TITLE
Feature Request: Part of speech tagging

### ISSUE THREAD

**Issue by benmarwick** [JuliaText/TextAnalysis.jl#2]
This would be great, the R packages are slow and haven't been updated for years...

**Comment by oxinabox** [comment]
At a skim, yes, that looks like a good guide for writing a POS tagger.

**Comment by Ayushk4** [comment]
@aviks I think we can close this issue.
In #131, YashPatel implemented the avg perceptron POS Tagger.

Also, a neural network based POS tagger was added in #169 that gives >90% accuracy on CoNLL 2003, 2000, GMB. ([link](https://github.com/Ayushk4/POS.jl/tree/master/valid))
