### ISSUE TITLE
Provide libstemmer through Yggdrasil

### ISSUE THREAD

**Issue by ViralBShah** [JuliaText/TextAnalysis.jl#204]
It would be nice to move this package to using artifacts to provide libstemmer.

**Comment by ViralBShah** [comment]
@aviks Is there someone in here who might be interested in this one?

**Comment by aviks** [comment]
There is already a  Snowball_jll and a Snowball.jl.  It's not yet integrated with the larger textanalysis package, but that should be simple. I'm just waiting for some other reorganisation in this package to happen first.

**Comment by ViralBShah** [comment]
Bump on this.

**Comment by ViralBShah** [comment]
This is now one of the last major packages that does not yet use artifacts.

**Comment by aviks** [comment]
v0.7.0 uses a jll.
