### ISSUE TITLE
Statistical tokenization algorithms 

### ISSUE THREAD

**Issue by tejasvaidhyadev** [JuliaText/TextAnalysis.jl#207]
Hi @aviks and @Oxinabox
**Statical tokenizers** are used in lot of **Transformer based models** including BERT family becasue of their ablity to tackle out of vocabulary problem.
After going through Tokenizers in `WordTokenizers.jl` which i think is pretty good and fast and it will be great if we can **built statical tokenizers** like BPE, unigram language models etc.  on top of it.
I have gone through the following papers-
[BPE](https://www.aclweb.org/anthology/P16-1162/)
[unigram language model](https://arxiv.org/abs/1804.10959) 
any suggestions how to proceed ?
Where should we keep it in `TextAnlaysis.jl` or `WordTokenizers.jl` ?

**Comment by aviks** [comment]
I think this should go into the WordTokenizers.jl. Unless there are big new dependencies, in which case they should probably go in its own package.

**Comment by oxinabox** [comment]
Closing in favor of 
https://github.com/JuliaText/WordTokenizers.jl/issues/44
