### ISSUE TITLE
Julia TextAnalysis NERTagger

### ISSUE THREAD

**Issue by mitrabhanu** [JuliaText/TextAnalysis.jl#214]
Julia TextAnalysis NERTagger is not working. I have followed documentation at https://juliatext.github.io/TextAnalysis.jl/dev/ner/

I have julia version 1.4.0.
I have added TextAnalysis Package using 
    Pkg.add("TextAnalysis")
I then tried Nertagger using command 
    ner = NERTagger()
But I get the below error
    ERROR: UndefVarError: NERTagger not defined

Please help.

**Comment by tejasvaidhyadev** [comment]
try adding `master` branch of TextAnalysis

**Comment by aviks** [comment]
This feature is now in TextModels.jl
