### ISSUE TITLE
Seems there are some typos in documents

### ISSUE THREAD

**Issue by chuchuHank** [JuliaText/TextAnalysis.jl#249]
In the document Preprocessing Documents section:
https://juliahub.com/docs/TextAnalysis/5Mwet/0.7.2/documents/#Preprocessing-Documents

In line 384,
prepare!(sd, strip_preposition) do not work but prepare!(sd, strip_prepositions) work.

In line 389,
prepare!(sd, strip_spares_terms) do not work but prepare!(sd, strip_sparse_terms) work.

**Comment by rssdev10** [comment]
thanks, fixed in #277
