### ISSUE TITLE
StringIndexError when trying to create a StringDocument based on a UTF8 string

### ISSUE THREAD

**Issue by alexzandros** [JuliaText/TextAnalysis.jl#255]
I'm trying to create a StringDocument based on a string that contains utf-8 characters, and all i'm getting is a `StringIndexError`

My code is as follows
 ```julia
str = "Lo que tengamos que hacer, apoyar, enteegar el ❤️ y el alma por nuestro país. Ivan es el Man. 👏👏👏#Duquepresidente https://t.co/Dr1LdTa5yQ"
sd = StringDocument(str)
````
And I get the following error
```
Error showing value of type StringDocument{String}:
ERROR: StringIndexError: invalid index [50], valid nearby indices [48]=>'❤', [51]=>'️'
```
Followed by a stack trace.

So, I need to know what is the best practice for working with utf strings.

Thanks in advance.

**Comment by aviks** [comment]
Can you paste the stack trace you saw? Looks like a bug on our side.

**Comment by segunolulana** [comment]
I also experienced the same issue. The text in question is "Less likely working with code I don’t like" and the stacktrace is

**Comment by rssdev10** [comment]
Not reproducible with Julia 1.9 and TextAnalysis 0.8
