### ISSUE TITLE
Libstemmer not defined for ARM (M1 Mac)

### ISSUE THREAD

**Issue by krishpa2** [JuliaText/TextAnalysis.jl#263]
Computer: M1 MacBook Pro

I installed the experimental 1.8.0-rc3 version of Julia in order to get native ARM support. I added every package I needed without errors except for TextAnalysis.jl. I have a small preprocessing file that cleans a document using standard NLP preprocessing (such as stemming, stop word removal, etc.), yet it throws an error when the stemming portion is called. 

I believe this is an ARM-related issue, as this same code works without issues when I use Julia 1.6 (via Rosetta). 

<img width="734" alt="image" src="https://user-images.githubusercontent.com/13796805/180352270-ba39e446-3664-4acb-abc5-fbf88d032b19.png">
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/13796805/180352324-25767b8a-9396-432b-8a1c-80e8ec119385.png">

**Comment by aviks** [comment]
Yeah, libstemmer needs to be recompiled in Yggdrasil for the ARM mac. https://github.com/JuliaPackaging/Yggdrasil/blob/master/S/Snowball/build_tarballs.jl

**Comment by aviks** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/5321

**Comment by aviks** [comment]
if you update your environment, this should now be fixed.
