### ISSUE TITLE
Extend compat for StatsBase to include v0.34

### ISSUE THREAD

**Issue by ablaom** [JuliaText/TextAnalysis.jl#267]
Evidently, CompatHelper needs a kick.

This is holding up downstream packages updates. See, e.g. issue linked below.

Thanks in advance.

**Comment by ablaom** [comment]
@aviks Sorry to nag, but this holding up MLJText.jl (see also https://github.com/alan-turing-institute/MLJ.jl/issues/1022)

**Comment by aviks** [comment]
Fixed via #268 and https://github.com/JuliaRegistries/General/pull/84210

**Comment by ablaom** [comment]
Thank you ❤️
