### ISSUE TITLE
Stemmer implementation

### ISSUE THREAD

**Issue by tanmaykm** [JuliaText/TextAnalysis.jl#3]
The `stem!` method currently is a stub. It would be very useful to have a stemmer integrated.

What is the direction to be taken to add a stemmer? Would wrapping the snowball stemmer from http://snowball.tartarus.org/ be a good approach? What are the other good alternatives?

**Comment by aviks** [comment]
For the record, @mguzmann 's porter stemmer is now at : https://github.com/mguzmann/CorpusTools/blob/master/src/PortStemmer.jl

It would certainly be an interesting project to port the stemmers. It may be reasonable to write snowball generators for the stemmers.. that will give us all stemmers at once.  But I think getting good performance out Julia stemmers is going to be a problem. 

The snowball stemmers work well, but need to be locally compiled. Finding a precompiled binary for windows is turning out to be an issue.

**Comment by mguzmann** [comment]
If there is any interest for it I could port the rest of the stemmers, I just wasn't sure people would be interested.
