### ISSUE TITLE
Problem creating a Corpus

### ISSUE THREAD

**Issue by rogerwhitney** [JuliaText/TextAnalysis.jl#46]
I am still a bit new to Julia so perhaps I am missing something basic here. When I try to create a Corpus following the example in the documentation (after correcting for the change in syntax) using:

Corpus([StringDocument("Document 1"), StringDocument("Document 2")])

I get the error:

MethodError: Cannot `convert` an object of type Array{TextAnalysis.StringDocument,1} to an object of type TextAnalysis.Corpus

I am using Julia 0.5 and the latest tag version of TextAnalysis

**Comment by rogerwhitney** [comment]
I should have waited a bit before creating the issue. I see the syntax is 

Corpus(Any[StringDocument("Document 1"), StringDocument("Document 2")])

**Comment by aviks** [comment]
Yes, actually, the way you wrote the code originally should be possible, needs an additional constructor.  I'll fix this soon, but for now you have the correct workaround.

**Comment by emilemathieu** [comment]
An additional constructor would indeed be useful.
A workaround is using the following syntax `Corpus(Any[array_of_documents...])`.

**Comment by laschuet** [comment]
This issue can be closed or am I missing something?

Running `Corpus([StringDocument("Document 1"), StringDocument("Document 2")])` in Julia 1.0.3 with latest `TextAnalysis` works and returns
```
Corpus{StringDocument{String}}(StringDocument{String}[
StringDocument{String}("Document 1", DocumentMetadata(English(), "Unnamed Document", "Unknown Author", "Unknown Time")),
StringDocument{String}("Document 2", DocumentMetadata(English(), "Unnamed Document", "Unknown Author", "Unknown Time"))
],
0,
Dict{String,Int64}(),
Dict{String,Array{Int64,1}}(),
TextHashFunction(hash, 100))
```
The current documentation still mentions `Corpus(Any[StringDocument("")])` etc.

**Comment by aviks** [comment]
Yes, the docs need changing, but the flexile constructor was implemented some time ago.
