### ISSUE TITLE
stemming issue for certain words e.g. providing -> provid

### ISSUE THREAD

**Issue by tk3369** [JuliaText/TextAnalysis.jl#69]
Some words are not converted properly.  Probably a libstemmer issue but that repo doesn't seem to be active so I'm posting here :-) 

```
julia> sm = TextAnalysis.stemmer_for_document(StringDocument("hello"))
Stemmer algorithm:english encoding:UTF_8

julia> stem(sm, "coming")
"come"

julia> stem(sm, "coding")
"code"

julia> stem(sm, "providing")
"provid"

julia> stem(sm, "improvising")
"improvis"

julia> stem(sm, "pursuing")
"pursu"

```

**Comment by aviks** [comment]
Not sure what we can do about this. Everyone just seems to use the Snowball stemmer.

**Comment by rssdev10** [comment]
https://snowballstem.org/ and a wrapper https://github.com/JuliaText/Snowball.jl
