### ISSUE TITLE
Unable to train new pattern for models

### ISSUE THREAD

**Issue by NapsterSL** [JuliaText/TextAnalysis.jl#73]
Hi,

I am new to Grobid Tool. I need to train some new patterns for citation model. Build is successful, while trying to train, giving exception:
![issue](https://user-images.githubusercontent.com/37894927/38075737-0be28da2-3351-11e8-9d3b-c5886b6430f5.png)

java.lang.unsatisfiedlinkerror, cudnt resolve this issue. I am using win-64.

**Comment by aviks** [comment]
Did you mean to raise this issue is some other repository? The GrobId repository is here: https://github.com/kermitt2/grobid

**Comment by NapsterSL** [comment]
Ok...Yes. Thank U!
