### ISSUE TITLE
Error while using the package for the first time

### ISSUE THREAD

**Issue by emilmirzayev** [JuliaText/TextAnalysis.jl#87]
Hi,
when using the package I receive these error messages and dozen of warnings:
`using TextAnalysis`
....................................
`ERROR: LoadError: LoadError: UndefVarError: SimpleVector not defined.`
`ERROR: LoadError: LoadError: Failed to precompile BSON [fbb218c0-5317-5bc6-957e-2ee96dd4b1f0] to C:\Users\emirzayev\.julia\compiled\v0.7\BSON\3tVCZ.ji.`
`ERROR: Failed to precompile TextAnalysis [a2db99b7-8b79-58f8-94bf-bbc811eef33d] to C:\Users\emirzayev\.julia\compiled\v0.7\TextAnalysis\5Mwet.ji.`

Julia version:
**Version 0.7.0 (2018-08-08 06:46 UTC)**
Install method:
**Downloading exe file**

**Comment by aviks** [comment]
Unfortunately, this package is not yet ready for 0.7/1.0.

**Comment by aviks** [comment]
Should be fine now.
